---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-photoshop-deployment
  namespace: database-photoshop
  labels:
    app: photoshop-database-test-server
    project: photoshop
    environment: prod
    purpose: poc
  annotations:
    kubernetes.io/change-cause: "v1 Database deployment"
    # the namespace in which the deployment will be created

spec:
  replicas: 1
  selector:
    matchLabels:
      # the selector to match the labels of the pods created by this deployment
      app: photoshop-database-test-server
      project: photoshop
      environment: prod
      purpose: poc

  # the pod template
  template:
    metadata:
      labels:
        app: photoshop-database-test-server
        project: photoshop
        environment: prod
        purpose: poc
    spec:
      containers:
        - name: database
          image: busybox
          command: ["sleep", "3600" ]
          # always pull the image to ensure we get the latest version of the application
          imagePullPolicy: Always
          volumeMounts:
            - name: mysql-data
              mountPath: /data

      nodeSelector:
        topology.kubernetes.io/zone: us-east-1b

      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: ebs-static-photoshop
---






