---




apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: database-photoshop
data:
  
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: photoshop_db
  
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-photoshop-deployment-test
  namespace: database-photoshop
  labels:
    app: photoshop-database-test-server
    project: photoshop-test
    environment: prod-test
    purpose: poc-test
  annotations:
    kubernetes.io/change-cause: "v1 Database deployment"
    # the namespace in which the deployment will be created

spec:
  replicas: 1
  selector:
    matchLabels:
      # the selector to match the labels of the pods created by this deployment
      app: photoshop-database-test-server
      project: photoshop-test
      environment: prod-test
      purpose: poc-test

  # the pod template
  template:
    metadata:
      labels:
        app: photoshop-database-test-server
        project: photoshop-test
        environment: prod-test
        purpose: poc-test
    spec:
      containers:
        - name: database
          # image: busybox
          image: sandeep0109/photobooth-k8s:database-2.2.2
          # command: ["sleep", "3600" ]
          # always pull the image to ensure we get the latest version of the application
          imagePullPolicy: Always
          # volumeMounts:
          #   - name: mysql-data
          #     mountPath: /data
          envFrom:  
            - configMapRef:   
              name: database-config
          
      nodeSelector:
        topology.kubernetes.io/zone: us-east-1b

      # volumes:
      #   - name: mysql-data
      #     persistentVolumeClaim:
      #       claimName: ebs-static-photoshop
---






